project_name = "MyAdvancedProject"
#version = "0.1.beta"
database_url = "mysql://user:pass@host:3306/app_db"
debug_mode = false
allowed_hosts = ["prod.example.com", "api.example.com"]
#port = 8080

[user]
username = "root"
password = "12345678"

[[prompts]]
name = "greeting"
value = 4
[[prompts]]
name = "farewell"
value = 2